// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDusb7O-A00TW2sszJPRQeZj5MZKy02Qv4',
    appId: '1:122084102652:web:fab97920c7085ba0fb2279',
    messagingSenderId: '122084102652',
    projectId: 'dashkai-auth',
    authDomain: 'dashkai-auth.firebaseapp.com',
    storageBucket: 'dashkai-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5n5_FntnVRWFsfu1w1Tn_RzNzJGEsrAc',
    appId: '1:122084102652:android:6ad6ac47a5d5800ffb2279',
    messagingSenderId: '122084102652',
    projectId: 'dashkai-auth',
    storageBucket: 'dashkai-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4pg1w-r7im6Rv5LJdfVMlyi2LGSwoqk',
    appId: '1:122084102652:ios:e4b96c0202c3f115fb2279',
    messagingSenderId: '122084102652',
    projectId: 'dashkai-auth',
    storageBucket: 'dashkai-auth.appspot.com',
    iosBundleId: 'com.example.dashkai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4pg1w-r7im6Rv5LJdfVMlyi2LGSwoqk',
    appId: '1:122084102652:ios:5ba7ac0e9ed8fd07fb2279',
    messagingSenderId: '122084102652',
    projectId: 'dashkai-auth',
    storageBucket: 'dashkai-auth.appspot.com',
    iosBundleId: 'com.example.dashkai.RunnerTests',
  );
}
